AllCops:
  RunRailsCops: true
  Include:
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
