# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9359a2828fa6102ba6e4866ab42cec735f93aa3d4bf76883f57a14f8f2fb570080e4a50f384cb8630275da9c6b82dfa6061d5b53ea37b21cba04af995f5fc2fa

test:
  secret_key_base: c0e19bde9e42a8d115ed022056830aa520ca2a18949f9ed631ce5371b310d23a2fbecf8d5bfc6fc1f0233cf07c4e965c16a4a7cc154e176b2853325aa1bee337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
